public final class kotlinx.coroutines.ExceptionsKt extends java.lang.Object
{

    public static final java.util.concurrent.CancellationException CancellationException(java.lang.String, java.lang.Throwable)
    {
        java.lang.String $r0;
        java.lang.Throwable $r1;
        java.util.concurrent.CancellationException $r2;

        $r0 := @parameter0: java.lang.String;

        $r1 := @parameter1: java.lang.Throwable;

        $r2 = new java.util.concurrent.CancellationException;

        specialinvoke $r2.<java.util.concurrent.CancellationException: void <init>(java.lang.String)>($r0);

        virtualinvoke $r2.<java.util.concurrent.CancellationException: java.lang.Throwable initCause(java.lang.Throwable)>($r1);

        return $r2;
    }

    public static final void addSuppressedThrowable(java.lang.Throwable, java.lang.Throwable)
    {
        java.lang.Throwable $r0, $r1;

        $r0 := @parameter0: java.lang.Throwable;

        $r1 := @parameter1: java.lang.Throwable;

        staticinvoke <kotlin.ExceptionsKt: void addSuppressed(java.lang.Throwable,java.lang.Throwable)>($r0, $r1);

        return;
    }
}
