final class kotlinx.coroutines.ResumeAwaitOnCompletion extends kotlinx.coroutines.JobNode
{
    private final kotlinx.coroutines.CancellableContinuationImpl continuation;

    public void <init>(kotlinx.coroutines.CancellableContinuationImpl)
    {
        kotlinx.coroutines.ResumeAwaitOnCompletion r0;
        kotlinx.coroutines.CancellableContinuationImpl $r1;

        r0 := @this: kotlinx.coroutines.ResumeAwaitOnCompletion;

        $r1 := @parameter0: kotlinx.coroutines.CancellableContinuationImpl;

        specialinvoke r0.<kotlinx.coroutines.JobNode: void <init>()>();

        r0.<kotlinx.coroutines.ResumeAwaitOnCompletion: kotlinx.coroutines.CancellableContinuationImpl continuation> = $r1;

        return;
    }

    public volatile java.lang.Object invoke(java.lang.Object)
    {
        kotlinx.coroutines.ResumeAwaitOnCompletion r0;
        java.lang.Object $r1;
        java.lang.Throwable $r2;
        kotlin.Unit r3;

        r0 := @this: kotlinx.coroutines.ResumeAwaitOnCompletion;

        $r1 := @parameter0: java.lang.Object;

        $r2 = (java.lang.Throwable) $r1;

        virtualinvoke r0.<kotlinx.coroutines.ResumeAwaitOnCompletion: void invoke(java.lang.Throwable)>($r2);

        r3 = <kotlin.Unit: kotlin.Unit INSTANCE>;

        return r3;
    }

    public void invoke(java.lang.Throwable)
    {
        kotlinx.coroutines.ResumeAwaitOnCompletion r0;
        java.lang.Throwable $r1;
        kotlinx.coroutines.JobSupport $r2;
        java.lang.Object $r3;
        boolean $z0;
        java.lang.AssertionError $r4;
        kotlinx.coroutines.CancellableContinuationImpl $r5;
        kotlin.coroutines.Continuation $r6;
        kotlinx.coroutines.CompletedExceptionally $r7;
        kotlin.Result$Companion $r8;

        r0 := @this: kotlinx.coroutines.ResumeAwaitOnCompletion;

        $r1 := @parameter0: java.lang.Throwable;

        $r2 = virtualinvoke r0.<kotlinx.coroutines.ResumeAwaitOnCompletion: kotlinx.coroutines.JobSupport getJob()>();

        $r3 = virtualinvoke $r2.<kotlinx.coroutines.JobSupport: java.lang.Object getState$kotlinx_coroutines_core()>();

        $z0 = staticinvoke <kotlinx.coroutines.DebugKt: boolean getASSERTIONS_ENABLED()>();

        if $z0 == 0 goto label2;

        $z0 = $r3 instanceof kotlinx.coroutines.Incomplete;

        $z0 = $z0 ^ 1;

        if $z0 == 0 goto label1;

        goto label2;

     label1:
        $r4 = new java.lang.AssertionError;

        specialinvoke $r4.<java.lang.AssertionError: void <init>()>();

        throw $r4;

     label2:
        $z0 = $r3 instanceof kotlinx.coroutines.CompletedExceptionally;

        if $z0 == 0 goto label3;

        $r5 = r0.<kotlinx.coroutines.ResumeAwaitOnCompletion: kotlinx.coroutines.CancellableContinuationImpl continuation>;

        $r6 = (kotlin.coroutines.Continuation) $r5;

        $r7 = (kotlinx.coroutines.CompletedExceptionally) $r3;

        $r1 = $r7.<kotlinx.coroutines.CompletedExceptionally: java.lang.Throwable cause>;

        $r8 = <kotlin.Result: kotlin.Result$Companion Companion>;

        $r3 = staticinvoke <kotlin.ResultKt: java.lang.Object createFailure(java.lang.Throwable)>($r1);

        $r3 = staticinvoke <kotlin.Result: java.lang.Object constructor-impl(java.lang.Object)>($r3);

        interfaceinvoke $r6.<kotlin.coroutines.Continuation: void resumeWith(java.lang.Object)>($r3);

        return;

     label3:
        $r5 = r0.<kotlinx.coroutines.ResumeAwaitOnCompletion: kotlinx.coroutines.CancellableContinuationImpl continuation>;

        $r6 = (kotlin.coroutines.Continuation) $r5;

        $r3 = staticinvoke <kotlinx.coroutines.JobSupportKt: java.lang.Object unboxState(java.lang.Object)>($r3);

        $r8 = <kotlin.Result: kotlin.Result$Companion Companion>;

        $r3 = staticinvoke <kotlin.Result: java.lang.Object constructor-impl(java.lang.Object)>($r3);

        interfaceinvoke $r6.<kotlin.coroutines.Continuation: void resumeWith(java.lang.Object)>($r3);

        return;
    }
}
