final class kotlinx.coroutines.flow.FlowKt__ErrorsKt extends java.lang.Object
{

    public static void ExceptionPredicate$annotations()
    {
        return;
    }

    public static final kotlinx.coroutines.flow.Flow 'catch'(kotlinx.coroutines.flow.Flow, kotlin.jvm.functions.Function3)
    {
        kotlinx.coroutines.flow.Flow $r0;
        kotlin.jvm.functions.Function3 $r1;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1 $r2;

        $r0 := @parameter0: kotlinx.coroutines.flow.Flow;

        $r1 := @parameter1: kotlin.jvm.functions.Function3;

        $r2 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1;

        specialinvoke $r2.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1: void <init>(kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function3)>($r0, $r1);

        $r0 = (kotlinx.coroutines.flow.Flow) $r2;

        return $r0;
    }

    public static final java.lang.Object catchImpl(kotlinx.coroutines.flow.Flow, kotlinx.coroutines.flow.FlowCollector, kotlin.coroutines.Continuation)
    {
        kotlinx.coroutines.flow.Flow $r0;
        kotlinx.coroutines.flow.FlowCollector $r1;
        kotlin.coroutines.Continuation $r2;
        boolean $z0;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1 $r3;
        int $i0;
        java.lang.Object $r4, $r5;
        kotlin.jvm.internal.Ref$ObjectRef $r6;
        java.lang.Throwable $r7, $r10;
        java.lang.IllegalStateException $r8;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1 $r9;
        kotlin.coroutines.CoroutineContext $r11;

        $r0 := @parameter0: kotlinx.coroutines.flow.Flow;

        $r1 := @parameter1: kotlinx.coroutines.flow.FlowCollector;

        $r2 := @parameter2: kotlin.coroutines.Continuation;

        $z0 = $r2 instanceof kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1;

        if $z0 == 0 goto label01;

        $r3 = (kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1) $r2;

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: int label>;

        $i0 = $i0 & -2147483648;

        if $i0 == 0 goto label01;

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: int label>;

        $i0 = $i0 - -2147483648;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: int label> = $i0;

        goto label02;

     label01:
        $r3 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1;

        specialinvoke $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: void <init>(kotlin.coroutines.Continuation)>($r2);

     label02:
        $r4 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: java.lang.Object result>;

        $r5 = staticinvoke <kotlin.coroutines.intrinsics.IntrinsicsKt: java.lang.Object getCOROUTINE_SUSPENDED()>();

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: int label>;

        if $i0 == 0 goto label07;

        if $i0 != 1 goto label06;

        $r5 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: java.lang.Object L$0>;

        $r6 = (kotlin.jvm.internal.Ref$ObjectRef) $r5;

     label03:
        staticinvoke <kotlin.ResultKt: void throwOnFailure(java.lang.Object)>($r4);

     label04:
        goto label10;

     label05:
        $r7 := @caughtexception;

        goto label12;

     label06:
        $r8 = new java.lang.IllegalStateException;

        specialinvoke $r8.<java.lang.IllegalStateException: void <init>(java.lang.String)>("call to \'resume\' before \'invoke\' with coroutine");

        throw $r8;

     label07:
        staticinvoke <kotlin.ResultKt: void throwOnFailure(java.lang.Object)>($r4);

        $r6 = new kotlin.jvm.internal.Ref$ObjectRef;

        specialinvoke $r6.<kotlin.jvm.internal.Ref$ObjectRef: void <init>()>();

     label08:
        $r9 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1;

        specialinvoke $r9.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1: void <init>(kotlinx.coroutines.flow.FlowCollector,kotlin.jvm.internal.Ref$ObjectRef)>($r1, $r6);

        $r1 = (kotlinx.coroutines.flow.FlowCollector) $r9;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: java.lang.Object L$0> = $r6;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$1: int label> = 1;

        $r4 = interfaceinvoke $r0.<kotlinx.coroutines.flow.Flow: java.lang.Object collect(kotlinx.coroutines.flow.FlowCollector,kotlin.coroutines.Continuation)>($r1, $r3);

     label09:
        if $r4 != $r5 goto label10;

        return $r5;

     label10:
        return null;

     label11:
        $r7 := @caughtexception;

     label12:
        $r4 = $r6.<kotlin.jvm.internal.Ref$ObjectRef: java.lang.Object element>;

        $r10 = (java.lang.Throwable) $r4;

        $z0 = staticinvoke <kotlinx.coroutines.flow.FlowKt__ErrorsKt: boolean isSameExceptionAs$FlowKt__ErrorsKt(java.lang.Throwable,java.lang.Throwable)>($r7, $r10);

        if $z0 != 0 goto label13;

        $r11 = interfaceinvoke $r3.<kotlin.coroutines.Continuation: kotlin.coroutines.CoroutineContext getContext()>();

        $z0 = staticinvoke <kotlinx.coroutines.flow.FlowKt__ErrorsKt: boolean isCancellationCause$FlowKt__ErrorsKt(java.lang.Throwable,kotlin.coroutines.CoroutineContext)>($r7, $r11);

        if $z0 != 0 goto label13;

        return $r7;

     label13:
        throw $r7;

        catch java.lang.Throwable from label03 to label04 with label05;
        catch java.lang.Throwable from label08 to label09 with label11;
    }

    private static final boolean isCancellationCause$FlowKt__ErrorsKt(java.lang.Throwable, kotlin.coroutines.CoroutineContext)
    {
        java.lang.Throwable $r0, $r7;
        kotlin.coroutines.CoroutineContext $r1;
        kotlinx.coroutines.Job$Key $r2;
        kotlin.coroutines.CoroutineContext$Key $r3;
        kotlin.coroutines.CoroutineContext$Element $r4;
        kotlinx.coroutines.Job $r5;
        boolean $z0;
        java.util.concurrent.CancellationException $r6;

        $r0 := @parameter0: java.lang.Throwable;

        $r1 := @parameter1: kotlin.coroutines.CoroutineContext;

        $r2 = <kotlinx.coroutines.Job: kotlinx.coroutines.Job$Key Key>;

        $r3 = (kotlin.coroutines.CoroutineContext$Key) $r2;

        $r4 = interfaceinvoke $r1.<kotlin.coroutines.CoroutineContext: kotlin.coroutines.CoroutineContext$Element get(kotlin.coroutines.CoroutineContext$Key)>($r3);

        $r5 = (kotlinx.coroutines.Job) $r4;

        if $r5 == null goto label2;

        $z0 = interfaceinvoke $r5.<kotlinx.coroutines.Job: boolean isCancelled()>();

        if $z0 != 0 goto label1;

        goto label2;

     label1:
        $r6 = interfaceinvoke $r5.<kotlinx.coroutines.Job: java.util.concurrent.CancellationException getCancellationException()>();

        $r7 = (java.lang.Throwable) $r6;

        $z0 = staticinvoke <kotlinx.coroutines.flow.FlowKt__ErrorsKt: boolean isSameExceptionAs$FlowKt__ErrorsKt(java.lang.Throwable,java.lang.Throwable)>($r0, $r7);

        return $z0;

     label2:
        return 0;
    }

    private static final boolean isSameExceptionAs$FlowKt__ErrorsKt(java.lang.Throwable, java.lang.Throwable)
    {
        java.lang.Throwable $r0, $r1;
        boolean $z0;

        $r0 := @parameter0: java.lang.Throwable;

        $r1 := @parameter1: java.lang.Throwable;

        if $r1 == null goto label5;

        $z0 = staticinvoke <kotlinx.coroutines.DebugKt: boolean getRECOVER_STACK_TRACES()>();

        if $z0 != 0 goto label1;

        goto label2;

     label1:
        $r1 = staticinvoke <kotlinx.coroutines.internal.StackTraceRecoveryKt: java.lang.Throwable unwrapImpl(java.lang.Throwable)>($r1);

     label2:
        $z0 = staticinvoke <kotlinx.coroutines.DebugKt: boolean getRECOVER_STACK_TRACES()>();

        if $z0 != 0 goto label3;

        goto label4;

     label3:
        $r0 = staticinvoke <kotlinx.coroutines.internal.StackTraceRecoveryKt: java.lang.Throwable unwrapImpl(java.lang.Throwable)>($r0);

     label4:
        $z0 = staticinvoke <kotlin.jvm.internal.Intrinsics: boolean areEqual(java.lang.Object,java.lang.Object)>($r1, $r0);

        if $z0 == 0 goto label5;

        return 1;

     label5:
        return 0;
    }

    public static final kotlinx.coroutines.flow.Flow onErrorCollect(kotlinx.coroutines.flow.Flow, kotlinx.coroutines.flow.Flow, kotlin.jvm.functions.Function1)
    {
        kotlinx.coroutines.flow.Flow $r0, $r2;
        kotlin.jvm.functions.Function1 $r1;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$2 $r3;
        kotlin.jvm.functions.Function3 $r4;

        $r2 := @parameter0: kotlinx.coroutines.flow.Flow;

        $r0 := @parameter1: kotlinx.coroutines.flow.Flow;

        $r1 := @parameter2: kotlin.jvm.functions.Function1;

        $r3 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$2;

        specialinvoke $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$2: void <init>(kotlin.jvm.functions.Function1,kotlinx.coroutines.flow.Flow,kotlin.coroutines.Continuation)>($r1, $r0, null);

        $r4 = (kotlin.jvm.functions.Function3) $r3;

        $r2 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow 'catch'(kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function3)>($r2, $r4);

        return $r2;
    }

    public static kotlinx.coroutines.flow.Flow onErrorCollect$default(kotlinx.coroutines.flow.Flow, kotlinx.coroutines.flow.Flow, kotlin.jvm.functions.Function1, int, java.lang.Object)
    {
        kotlinx.coroutines.flow.Flow $r0, $r2;
        java.lang.Object $r1;
        kotlin.jvm.functions.Function1 $r3;
        int $i0;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$1 $r4;

        $r2 := @parameter0: kotlinx.coroutines.flow.Flow;

        $r0 := @parameter1: kotlinx.coroutines.flow.Flow;

        $r3 := @parameter2: kotlin.jvm.functions.Function1;

        $i0 := @parameter3: int;

        $r1 := @parameter4: java.lang.Object;

        $i0 = $i0 & 2;

        if $i0 == 0 goto label1;

        $r4 = <kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$1: kotlinx.coroutines.flow.FlowKt__ErrorsKt$onErrorCollect$1 INSTANCE>;

        $r3 = (kotlin.jvm.functions.Function1) $r4;

     label1:
        $r2 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow onErrorCollect(kotlinx.coroutines.flow.Flow,kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function1)>($r2, $r0, $r3);

        return $r2;
    }

    public static final kotlinx.coroutines.flow.Flow retry(kotlinx.coroutines.flow.Flow, int, kotlin.jvm.functions.Function1)
    {
        kotlin.jvm.functions.Function1 $r0;
        kotlinx.coroutines.flow.Flow $r1;
        int $i0;
        boolean $z0;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$6 $r2;
        kotlin.jvm.functions.Function4 $r3;
        java.lang.Integer $r4;
        java.lang.String $r5;
        java.lang.IllegalArgumentException $r6;
        java.lang.Throwable $r7;

        $r1 := @parameter0: kotlinx.coroutines.flow.Flow;

        $i0 := @parameter1: int;

        $r0 := @parameter2: kotlin.jvm.functions.Function1;

        if $i0 <= 0 goto label1;

        $z0 = 1;

        goto label2;

     label1:
        $z0 = 0;

     label2:
        if $z0 == 0 goto label3;

        $r2 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$6;

        specialinvoke $r2.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$6: void <init>(kotlin.jvm.functions.Function1,int,kotlin.coroutines.Continuation)>($r0, $i0, null);

        $r3 = (kotlin.jvm.functions.Function4) $r2;

        $r1 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow retryWhen(kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function4)>($r1, $r3);

        return $r1;

     label3:
        $r4 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>($i0);

        $r5 = staticinvoke <kotlin.jvm.internal.Intrinsics: java.lang.String stringPlus(java.lang.String,java.lang.Object)>("Expected positive amount of retries, but had ", $r4);

        $r6 = new java.lang.IllegalArgumentException;

        $r5 = virtualinvoke $r5.<java.lang.Object: java.lang.String toString()>();

        specialinvoke $r6.<java.lang.IllegalArgumentException: void <init>(java.lang.String)>($r5);

        $r7 = (java.lang.Throwable) $r6;

        throw $r7;
    }

    public static final kotlinx.coroutines.flow.Flow retry(kotlinx.coroutines.flow.Flow, long, kotlin.jvm.functions.Function2)
    {
        kotlin.jvm.functions.Function2 $r0;
        kotlinx.coroutines.flow.Flow $r1;
        long $l0;
        byte $b1;
        boolean $z0;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$3 $r2;
        kotlin.jvm.functions.Function4 $r3;
        java.lang.Long $r4;
        java.lang.String $r5;
        java.lang.IllegalArgumentException $r6;
        java.lang.Throwable $r7;

        $r1 := @parameter0: kotlinx.coroutines.flow.Flow;

        $l0 := @parameter1: long;

        $r0 := @parameter2: kotlin.jvm.functions.Function2;

        $b1 = $l0 cmp 0L;

        if $b1 <= 0 goto label1;

        $z0 = 1;

        goto label2;

     label1:
        $z0 = 0;

     label2:
        if $z0 == 0 goto label3;

        $r2 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$3;

        specialinvoke $r2.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$3: void <init>(long,kotlin.jvm.functions.Function2,kotlin.coroutines.Continuation)>($l0, $r0, null);

        $r3 = (kotlin.jvm.functions.Function4) $r2;

        $r1 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow retryWhen(kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function4)>($r1, $r3);

        return $r1;

     label3:
        $r4 = staticinvoke <java.lang.Long: java.lang.Long valueOf(long)>($l0);

        $r5 = staticinvoke <kotlin.jvm.internal.Intrinsics: java.lang.String stringPlus(java.lang.String,java.lang.Object)>("Expected positive amount of retries, but had ", $r4);

        $r6 = new java.lang.IllegalArgumentException;

        $r5 = virtualinvoke $r5.<java.lang.Object: java.lang.String toString()>();

        specialinvoke $r6.<java.lang.IllegalArgumentException: void <init>(java.lang.String)>($r5);

        $r7 = (java.lang.Throwable) $r6;

        throw $r7;
    }

    public static kotlinx.coroutines.flow.Flow retry$default(kotlinx.coroutines.flow.Flow, int, kotlin.jvm.functions.Function1, int, java.lang.Object)
    {
        kotlinx.coroutines.flow.Flow $r0;
        int $i0, $i1, $i2;
        kotlin.jvm.functions.Function1 $r1;
        java.lang.Object $r2;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$4 $r3;

        $r0 := @parameter0: kotlinx.coroutines.flow.Flow;

        $i0 := @parameter1: int;

        $r1 := @parameter2: kotlin.jvm.functions.Function1;

        $i1 := @parameter3: int;

        $r2 := @parameter4: java.lang.Object;

        $i2 = $i1 & 1;

        if $i2 == 0 goto label1;

        $i0 = 2147483647;

     label1:
        $i1 = $i1 & 2;

        if $i1 == 0 goto label2;

        $r3 = <kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$4: kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$4 INSTANCE>;

        $r1 = (kotlin.jvm.functions.Function1) $r3;

     label2:
        $r0 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow retry(kotlinx.coroutines.flow.Flow,int,kotlin.jvm.functions.Function1)>($r0, $i0, $r1);

        return $r0;
    }

    public static kotlinx.coroutines.flow.Flow retry$default(kotlinx.coroutines.flow.Flow, long, kotlin.jvm.functions.Function2, int, java.lang.Object)
    {
        kotlinx.coroutines.flow.Flow $r0;
        long $l0;
        kotlin.jvm.functions.Function2 $r1;
        int $i1, $i2;
        java.lang.Object $r2;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$1 $r3;

        $r0 := @parameter0: kotlinx.coroutines.flow.Flow;

        $l0 := @parameter1: long;

        $r1 := @parameter2: kotlin.jvm.functions.Function2;

        $i1 := @parameter3: int;

        $r2 := @parameter4: java.lang.Object;

        $i2 = $i1 & 1;

        if $i2 == 0 goto label1;

        $l0 = 9223372036854775807L;

     label1:
        $i1 = $i1 & 2;

        if $i1 == 0 goto label2;

        $r3 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$1;

        specialinvoke $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$retry$1: void <init>(kotlin.coroutines.Continuation)>(null);

        $r1 = (kotlin.jvm.functions.Function2) $r3;

     label2:
        $r0 = staticinvoke <kotlinx.coroutines.flow.FlowKt: kotlinx.coroutines.flow.Flow retry(kotlinx.coroutines.flow.Flow,long,kotlin.jvm.functions.Function2)>($r0, $l0, $r1);

        return $r0;
    }

    public static final kotlinx.coroutines.flow.Flow retryWhen(kotlinx.coroutines.flow.Flow, kotlin.jvm.functions.Function4)
    {
        kotlinx.coroutines.flow.Flow $r0;
        kotlin.jvm.functions.Function4 $r1;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$retryWhen$$inlined$unsafeFlow$1 $r2;

        $r0 := @parameter0: kotlinx.coroutines.flow.Flow;

        $r1 := @parameter1: kotlin.jvm.functions.Function4;

        $r2 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$retryWhen$$inlined$unsafeFlow$1;

        specialinvoke $r2.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$retryWhen$$inlined$unsafeFlow$1: void <init>(kotlinx.coroutines.flow.Flow,kotlin.jvm.functions.Function4)>($r0, $r1);

        $r0 = (kotlinx.coroutines.flow.Flow) $r2;

        return $r0;
    }
}
