public final class kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1 extends java.lang.Object implements kotlinx.coroutines.flow.FlowCollector
{
    final kotlinx.coroutines.flow.FlowCollector $collector$inlined;
    final kotlin.jvm.internal.Ref$ObjectRef $fromDownstream$inlined;

    public void <init>(kotlinx.coroutines.flow.FlowCollector, kotlin.jvm.internal.Ref$ObjectRef)
    {
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1 r0;
        kotlinx.coroutines.flow.FlowCollector $r1;
        kotlin.jvm.internal.Ref$ObjectRef $r2;

        r0 := @this: kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1;

        $r1 := @parameter0: kotlinx.coroutines.flow.FlowCollector;

        $r2 := @parameter1: kotlin.jvm.internal.Ref$ObjectRef;

        r0.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1: kotlinx.coroutines.flow.FlowCollector $collector$inlined> = $r1;

        r0.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1: kotlin.jvm.internal.Ref$ObjectRef $fromDownstream$inlined> = $r2;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        return;
    }

    public java.lang.Object emit(java.lang.Object, kotlin.coroutines.Continuation)
    {
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1 r0;
        java.lang.Object $r1, $r4, $r5;
        kotlin.coroutines.Continuation $r2;
        boolean $z0;
        kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1 $r3;
        int $i0;
        java.lang.Throwable $r6;
        java.lang.IllegalStateException $r7;
        kotlinx.coroutines.flow.FlowCollector $r8;
        kotlin.jvm.internal.Ref$ObjectRef $r9;
        kotlin.Unit r10;

        r0 := @this: kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1;

        $r1 := @parameter0: java.lang.Object;

        $r2 := @parameter1: kotlin.coroutines.Continuation;

        $z0 = $r2 instanceof kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1;

        if $z0 == 0 goto label01;

        $r3 = (kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1) $r2;

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: int label>;

        $i0 = $i0 & -2147483648;

        if $i0 == 0 goto label01;

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: int label>;

        $i0 = $i0 - -2147483648;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: int label> = $i0;

        goto label02;

     label01:
        $r3 = new kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1;

        specialinvoke $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: void <init>(kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1,kotlin.coroutines.Continuation)>(r0, $r2);

     label02:
        $r4 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: java.lang.Object result>;

        $r5 = staticinvoke <kotlin.coroutines.intrinsics.IntrinsicsKt: java.lang.Object getCOROUTINE_SUSPENDED()>();

        $i0 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: int label>;

        if $i0 == 0 goto label07;

        if $i0 != 1 goto label06;

        $r1 = $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: java.lang.Object L$0>;

        r0 = (kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1) $r1;

     label03:
        staticinvoke <kotlin.ResultKt: void throwOnFailure(java.lang.Object)>($r4);

     label04:
        goto label10;

     label05:
        $r6 := @caughtexception;

        goto label12;

     label06:
        $r7 = new java.lang.IllegalStateException;

        specialinvoke $r7.<java.lang.IllegalStateException: void <init>(java.lang.String)>("call to \'resume\' before \'invoke\' with coroutine");

        throw $r7;

     label07:
        staticinvoke <kotlin.ResultKt: void throwOnFailure(java.lang.Object)>($r4);

        $r2 = (kotlin.coroutines.Continuation) $r3;

     label08:
        $r8 = r0.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1: kotlinx.coroutines.flow.FlowCollector $collector$inlined>;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: java.lang.Object L$0> = r0;

        $r3.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1$1: int label> = 1;

        $r1 = interfaceinvoke $r8.<kotlinx.coroutines.flow.FlowCollector: java.lang.Object emit(java.lang.Object,kotlin.coroutines.Continuation)>($r1, $r3);

     label09:
        if $r1 != $r5 goto label10;

        return $r5;

     label10:
        r10 = <kotlin.Unit: kotlin.Unit INSTANCE>;

        return r10;

     label11:
        $r6 := @caughtexception;

     label12:
        $r9 = r0.<kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1: kotlin.jvm.internal.Ref$ObjectRef $fromDownstream$inlined>;

        $r9.<kotlin.jvm.internal.Ref$ObjectRef: java.lang.Object element> = $r6;

        throw $r6;

        catch java.lang.Throwable from label03 to label04 with label05;
        catch java.lang.Throwable from label08 to label09 with label11;
    }
}
